# Jekyll
permalink: pretty
paginate: 10
title: OpenStack4j
baseurl: ''
markdown: kramdown
version: 3.3
snapshot-version: 3.4-SNAPSHOT
url: https://openstack4j.github.io/

plugins: [jekyll-paginate]

pkgs:
  all:
    nginx
