# Jekyll
permalink: pretty
paginate: 10
name: OpenStack4j
baseurl: ''
markdown: kramdown
version: 3.1.0
snapshot-version: 3.1.1-SNAPSHOT
withdeps-version: 3.1.0-withdeps
maintenance-version: 2.20
url: http://www.openstack4j.com

gems: [jekyll-paginate]

exclude: [support, Dockerfile]
pkgs:
  all:
    nginx

theme: jekyll-theme-cayman